### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by Garkus98** [Anrolosia/Shopping-List-with-Grocy#25]
Hello. After installing and customizing your add-on here: on the computer in different browsers is crooked, but in the android app is normal well or so true with your picture does not match your picture 
![photo_2023-07-14_19-45-50](https://github.com/Anrolosia/Shopping-List-with-Grocy/assets/76440047/7d856a38-c78a-4349-af2a-232bb813c321)
![Снимок экрана 2023-07-14 194413](https://github.com/Anrolosia/Shopping-List-with-Grocy/assets/76440047/e1a83689-21c0-4e58-9c06-1a912ff927a1)
![Снимок экрана 2023-07-14 194710](https://github.com/Anrolosia/Shopping-List-with-Grocy/assets/76440047/8baf2a34-b9c6-4bc0-bfcc-b7da9955ca62)

**Comment by Garkus98** [comment]
I also noticed that adding 4 products to the shopping list in grocy, he is one of them in ha for some reason alternates and displays only 3 products

**Comment by Anrolosia** [comment]
Hello @Garkus98 ,
The UI is not part of that integration, it an example, you have to make it yours... Have you tried to remove `aspect_ratio: 4/3`? Or just change value?
For the other "problem", have you tried restarting your homeassistant instance? If your mqtt is overloaded, it could happen, but a restart usually works.
Thanks

**Comment by Garkus98** [comment]
aspect ratio and deleted and changed just changed the size. Can I ask you for a configuration as in the photo yaml ? I like it very easily. after restarting everything remains the same.

**Comment by Garkus98** [comment]
@Anrolosia AnrolosiaYou say that the integration does not provide the interface and users should create it themselves, but at the same time 1- not all users know how to master yaml and draw it 2- and could you expand the integration and make for example options for selecting the interface such as minimalist medium and large or advanced?

**Comment by Anrolosia** [comment]
Sorry @Garkus98 but I can't do that, this integration is only meant to provide Grocy's data (product, shopping list) and act on those, but how users want to diplay it is too complicated to deal with, because some will use custom:button-card (like me), maybe some others will use picture card, and some others html-card. This is up to everyton to choose how and what configuration is the easiest one.
That being said, the README file is pretty exhaustive here: [Example of dashboard UI](https://github.com/Anrolosia/Shopping-List-with-Grocy/blob/main/README.md#example-of-dashboard-ui) And as the title suggest, it's an example, it's not meant to be used out of the box

**Comment by Garkus98** [comment]
All right, well, I hear you, then I'll close the subject.
