### ISSUE TITLE
little question...

### ISSUE THREAD

**Issue by schumi2309** [Anrolosia/Shopping-List-with-Grocy#5]
It's me again, for another little problem.
I installed the grocy app on my iphone, but once outside my home, I don't have access to the grocy Home Assistant list! I have to do something special?
I have specified port 9192 and cut the SSL.
in the grocy app on my iphone, I put this as the server:
http://192.168.0.12:9192
with of course api

but when I'm outside, I no longer have my shopping list

**Comment by Anrolosia** [comment]
Hello,

this is not the right place to ask about that, I'm affiliated in any way to Grocy, I strongly suggest you to use their Github for any assistance: https://github.com/patzly/grocy-android

Also, an ip address like 192.168.x.x is a local address, that means it's only available inside your home network. You have to do the steps to enable remote access to your homeassistant in order to access services hosted by homeassistant. You have plenty of documentation on Google, but I suggest you to start here: https://www.home-assistant.io/docs/configuration/remote/

**Comment by schumi2309** [comment]
I am connected outside to home assistant via nabu casa.
here is the kind of url i have to connect to it:

https://wob7cnvoor******************.ui.nabu.casa/

If I put this url like that or with: 9192 it doesn't work!
so, how to do ?
